on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: azehmwreg.azurecr.io
        username: ${{ secrets.acr_azehmwreg_username }}
        password: ${{ secrets.acr_azehmwreg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t azehmwreg.azurecr.io/azehmwcluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push azehmwreg.azurecr.io/azehmwcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_azehmwcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aze-hmwcluster80c4 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aze-hmwcluster80c4`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aze-hmwcluster80c4
        container-registry-url: azehmwreg.azurecr.io
        container-registry-username: ${{ secrets.acr_azehmwreg_username }}
        container-registry-password: ${{ secrets.acr_azehmwreg_password }}
        secret-name: azehmwclustedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aze-hmwcluster80c4
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
          manifests/ingress-2.yml
        images: |
          azehmwreg.azurecr.io/azehmwcluster:${{ github.sha }}
        imagepullsecrets: |
          azehmwclustedockerauth
